# lib/generate.sh - artifact generation for erambox
#
# Maintainer: Cognis Digital
# License: COCL 1.0
#
# Renders a reproducible docker-compose.yml plus app, db, and proxy config
# files. Templates are clean-room originals authored here for a GENERIC GRC
# stack (web app + database + reverse proxy). Two profiles: dev and prod.

# --------------------------------------------------------------------------
# Template text. All placeholders are {{KEY}} resolved against array TV.
# --------------------------------------------------------------------------

_tpl_compose_header() {
cat <<'EOF'
# docker-compose.yml -- generated by erambox (Cognis Digital)
# Profile: {{ERAMBOX_PROFILE}}
# Generic self-hosted GRC stack: web app + database + reverse proxy.
# Regenerate with: erambox.sh generate --config <file> --profile {{ERAMBOX_PROFILE}}
name: {{APP_NAME}}

services:
  app:
    image: {{APP_IMAGE}}
    restart: unless-stopped
    environment:
      GRC_DB_HOST: db
      GRC_DB_PORT: "5432"
      GRC_DB_NAME: {{DB_NAME}}
      GRC_DB_USER: {{DB_USER}}
      GRC_DB_PASSWORD: {{DB_PASSWORD}}
      GRC_APP_SECRET: {{APP_SECRET_KEY}}
      GRC_LISTEN_PORT: "{{APP_INTERNAL_PORT}}"
      GRC_PUBLIC_HOSTNAME: {{PUBLIC_HOSTNAME}}
    volumes:
      - ./config/app.conf:/etc/grc/app.conf:ro
      - app_data:/var/lib/grc
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:{{APP_INTERNAL_PORT}}{{HEALTH_PATH}} || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
EOF
}

_tpl_compose_app_devports() {
cat <<'EOF'
    ports:
      - "{{APP_PORT}}:{{APP_INTERNAL_PORT}}"
EOF
}

_tpl_compose_app_expose() {
cat <<'EOF'
    expose:
      - "{{APP_INTERNAL_PORT}}"
EOF
}

_tpl_compose_db() {
cat <<'EOF'

  db:
    image: {{DB_IMAGE}}
    restart: unless-stopped
    environment:
      POSTGRES_DB: {{DB_NAME}}
      POSTGRES_USER: {{DB_USER}}
      POSTGRES_PASSWORD: {{DB_PASSWORD}}
    volumes:
      - ./config/db-init.sql:/docker-entrypoint-initdb.d/00-grc-init.sql:ro
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {{DB_USER}} -d {{DB_NAME}}"]
      interval: 10s
      timeout: 5s
      retries: 5
EOF
}

_tpl_compose_db_devports() {
cat <<'EOF'
    ports:
      - "{{DB_PORT}}:5432"
EOF
}

_tpl_compose_proxy_head() {
cat <<'EOF'

  proxy:
    image: {{PROXY_IMAGE}}
    restart: unless-stopped
    depends_on:
      app:
        condition: service_started
    volumes:
      - ./config/proxy.conf:/etc/nginx/conf.d/grc.conf:ro
EOF
}

_tpl_compose_proxy_tls_mounts() {
cat <<'EOF'
      - {{TLS_CERT_PATH}}:/etc/nginx/tls/cert.pem:ro
      - {{TLS_KEY_PATH}}:/etc/nginx/tls/key.pem:ro
EOF
}

_tpl_compose_proxy_ports_dev() {
cat <<'EOF'
    ports:
      - "{{PROXY_HTTP_PORT}}:80"
EOF
}

_tpl_compose_proxy_ports_prod() {
cat <<'EOF'
    ports:
      - "{{PROXY_HTTP_PORT}}:80"
      - "{{PROXY_HTTPS_PORT}}:443"
EOF
}

_tpl_compose_footer() {
cat <<'EOF'

volumes:
  app_data:
  db_data:

networks:
  default:
    name: {{APP_NAME}}_net
EOF
}

# ---- app.conf -------------------------------------------------------------
_tpl_app_conf() {
cat <<'EOF'
# app.conf -- generated by erambox (Cognis Digital)
# Generic GRC web application configuration. Profile: {{ERAMBOX_PROFILE}}

[server]
listen_port = {{APP_INTERNAL_PORT}}
public_hostname = {{PUBLIC_HOSTNAME}}
health_path = {{HEALTH_PATH}}
behind_proxy = true

[database]
host = db
port = 5432
name = {{DB_NAME}}
user = {{DB_USER}}

[security]
profile = {{ERAMBOX_PROFILE}}
secure_cookies = {{SECURE_COOKIES}}
hsts = {{HSTS_FLAG}}
EOF
}

# ---- db-init.sql ----------------------------------------------------------
_tpl_db_init() {
cat <<'EOF'
-- db-init.sql -- generated by erambox (Cognis Digital)
-- Minimal bootstrap for a generic GRC schema. Idempotent.

CREATE SCHEMA IF NOT EXISTS grc;

-- Core GRC object tables (generic; extend in your application layer).
CREATE TABLE IF NOT EXISTS grc.controls (
    id          BIGSERIAL PRIMARY KEY,
    ref         TEXT NOT NULL UNIQUE,
    title       TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS grc.risks (
    id          BIGSERIAL PRIMARY KEY,
    title       TEXT NOT NULL,
    likelihood  INTEGER NOT NULL DEFAULT 1,
    impact      INTEGER NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS grc.policies (
    id          BIGSERIAL PRIMARY KEY,
    name        TEXT NOT NULL,
    version     TEXT NOT NULL DEFAULT '1.0',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
EOF
}

# ---- proxy.conf (dev: http only) -----------------------------------------
_tpl_proxy_conf_dev() {
cat <<'EOF'
# proxy.conf -- generated by erambox (Cognis Digital)
# Reverse proxy (dev profile, HTTP only). Hostname: {{PUBLIC_HOSTNAME}}

upstream grc_app {
    server app:{{APP_INTERNAL_PORT}};
}

server {
    listen 80;
    server_name {{PUBLIC_HOSTNAME}};

    location {{HEALTH_PATH}} {
        proxy_pass http://grc_app;
        access_log off;
    }

    location / {
        proxy_pass http://grc_app;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
EOF
}

# ---- proxy.conf (prod: TLS + hardening + redirect) -----------------------
_tpl_proxy_conf_prod() {
cat <<'EOF'
# proxy.conf -- generated by erambox (Cognis Digital)
# Reverse proxy (prod profile, TLS + hardening). Hostname: {{PUBLIC_HOSTNAME}}

upstream grc_app {
    server app:{{APP_INTERNAL_PORT}};
}

# Redirect all plaintext traffic to HTTPS.
server {
    listen 80;
    server_name {{PUBLIC_HOSTNAME}};
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name {{PUBLIC_HOSTNAME}};

    ssl_certificate     /etc/nginx/tls/cert.pem;
    ssl_certificate_key /etc/nginx/tls/key.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # Hardening headers.
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    client_max_body_size 25m;

    location {{HEALTH_PATH}} {
        proxy_pass http://grc_app;
        access_log off;
    }

    location / {
        proxy_pass http://grc_app;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
EOF
}

# --------------------------------------------------------------------------
# generate_run PROFILE OUTDIR FORCE
# --------------------------------------------------------------------------
generate_run() {
  local profile="$1" outdir="$2" force="$3"

  # Build the template-values array from CFG plus derived flags.
  declare -A TV=()
  local k
  for k in "${ERAMBOX_KNOWN_KEYS[@]}"; do
    TV["$k"]="$(config_get "$k" "")"
  done
  # Ensure profile reflects the requested profile, not just the file's.
  TV[ERAMBOX_PROFILE]="$profile"
  # Defaults for placeholders that may be empty in dev.
  : "${TV[APP_SECRET_KEY]:=dev-insecure-secret}"
  : "${TV[APP_PORT]:=}"
  : "${TV[DB_PORT]:=}"
  : "${TV[PROXY_HTTP_PORT]:=}"
  : "${TV[PROXY_HTTPS_PORT]:=}"

  # Derived security flags by profile.
  if [ "$profile" = "prod" ]; then
    TV[SECURE_COOKIES]="true"
    TV[HSTS_FLAG]="true"
  else
    TV[SECURE_COOKIES]="false"
    TV[HSTS_FLAG]="false"
  fi

  ensure_outdir "$outdir" "$force"
  mkdir -p "$outdir/config"

  # ---- assemble docker-compose.yml --------------------------------------
  local compose=""
  compose+="$(_tpl_compose_header)"$'\n'
  if [ "$profile" = "prod" ]; then
    # In prod the app is not published on the host; only the proxy is.
    compose+="$(_tpl_compose_app_expose)"$'\n'
  else
    compose+="$(_tpl_compose_app_devports)"$'\n'
  fi

  compose+="$(_tpl_compose_db)"$'\n'
  if [ "$profile" = "dev" ] && [ -n "${TV[DB_PORT]}" ]; then
    compose+="$(_tpl_compose_db_devports)"$'\n'
  fi

  compose+="$(_tpl_compose_proxy_head)"$'\n'
  if [ "$profile" = "prod" ]; then
    compose+="$(_tpl_compose_proxy_tls_mounts)"$'\n'
    compose+="$(_tpl_compose_proxy_ports_prod)"$'\n'
  else
    compose+="$(_tpl_compose_proxy_ports_dev)"$'\n'
  fi

  compose+="$(_tpl_compose_footer)"$'\n'

  tpl_render_file "$compose" TV "$outdir/docker-compose.yml"

  # ---- app.conf ----------------------------------------------------------
  tpl_render_file "$(_tpl_app_conf)" TV "$outdir/config/app.conf"

  # ---- db-init.sql -------------------------------------------------------
  tpl_render_file "$(_tpl_db_init)" TV "$outdir/config/db-init.sql"

  # ---- proxy.conf --------------------------------------------------------
  if [ "$profile" = "prod" ]; then
    tpl_render_file "$(_tpl_proxy_conf_prod)" TV "$outdir/config/proxy.conf"
  else
    tpl_render_file "$(_tpl_proxy_conf_dev)" TV "$outdir/config/proxy.conf"
  fi

  log "generated artifacts in: $outdir"
  log "  docker-compose.yml"
  log "  config/app.conf"
  log "  config/db-init.sql"
  log "  config/proxy.conf"
}

# cmd_generate -- CLI entrypoint.
cmd_generate() {
  local config="" profile="" outdir="./out" force="false"
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --config)  require_value "$1" "${2-}"; config="$2"; shift 2 ;;
      --profile) require_value "$1" "${2-}"; profile="$2"; shift 2 ;;
      --out)     require_value "$1" "${2-}"; outdir="$2"; shift 2 ;;
      --force)   force="true"; shift ;;
      --help|-h) usage; return 0 ;;
      *) die "generate: unknown option '$1'" ;;
    esac
  done

  config_load "$config"
  config_apply_defaults
  [ -n "$profile" ] || profile="$(config_effective_profile dev)"

  # Refuse to generate from an invalid config.
  if ! validate_run "$profile"; then
    die "refusing to generate from an invalid config"
  fi

  generate_run "$profile" "$outdir" "$force"
}
